[package]
version = "0.1.0"
name = "evm-exec-types"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
bincode = { workspace = true }
celestia-types = { workspace = true }
hex = { workspace = true }
rsp-client-executor = { workspace = true }
serde = { workspace = true }
